package com.example;
import java.util.*;

class InterfaceDONOTUSE {
    // only one function that has a loop of looking for commands and executing them
    public void doInterface(Library library) {
        Scanner scanner = new Scanner(System.in);
        String input;
        String bookAuthor;
        String bookName;
        String bookGenre;
        int bookYear;
        String bookISBN;
        Book book;
        String memberName;
        String memberEmail;
        Member member;

        System.out.println("Welcome to the Library CLI! Type 'exit' to quit.");
        printMenu();

        while (true) {
            System.out.print("> ");
            input = scanner.nextLine().trim();


            if (input.equalsIgnoreCase("11") || input.equalsIgnoreCase("exit")) {
                System.out.println("Goodbye!");
                break;
            }

            switch (input.toLowerCase()) {
                case "hello": //    hello command
                    System.out.println("Hi there!");
                    printMenu();
                    break;
                case "10":
                    System.out.println("Choose number to select option:");
                    System.out.println("+-----------------------+");
                    System.out.println("1. Add Book");
                    System.out.println("2. Remove Book");
                    System.out.println("3. Update Book");
                    System.out.println("4. Add Member");
                    System.out.println("5. Remove Member");
                    System.out.println("6. Checkout Book");
                    System.out.println("7. Return Book");
                    System.out.println("8. Print Member Info");
                    System.out.println("9. Print All Books List");
                    System.out.println("10. Help");
                    System.out.println("11. Exit");
                    System.out.println("+-----------------------+");
                    break;
                case "1": // add book
                    // asks for all info about a book ands adds it to library book list
                    // always sets new book to available and bookID is auto-generated by Book constructor
                    System.out.println("Enter Book Title");
                    input = scanner.nextLine().trim();
                    bookName = input.toLowerCase();

                    System.out.println("Enter Book Author");
                    input = scanner.nextLine().trim();
                    bookAuthor = input.toLowerCase();

                    System.out.println("Enter Book Year");
                    input = scanner.nextLine().trim();
                    bookYear = Integer.parseInt(input);

                    System.out.println("Enter Book ISBN");
                    bookISBN = scanner.nextLine().trim();

                    System.out.println("Enter Book Genre");
                    input = scanner.nextLine().trim();
                    bookGenre = input.toLowerCase();

                    book = new Book(bookName, bookAuthor, bookYear,bookISBN, bookGenre, library);
                    library.addBook(book);
                    printMenu();
                    break;
                case "2": //  remove book
                    // removes a book with a given title from the library
                    System.out.println("Enter Book Title");
                    input = scanner.nextLine().trim();
                    String title = input.toLowerCase();
                    book = library.findBookIdByName(title);
                    library.removeBook(book);
                    System.out.println("Book " + title + " has been removed\n\n");
                    printMenu();
                    break;
                case "3": //  update book
                    // updates a given books info in the library
                    System.out.println("Enter Book Title");
                    String updateTitle = scanner.nextLine().trim().toLowerCase();
                    book = library.findBookIdByName(updateTitle);
                    if (book != null) { 
                        while(true) {
                        // asks for which info to update and updates it
                        System.out.println("What would you like to update?");
                        System.out.println("1. Update Title");
                        System.out.println("2. Update Author");
                        System.out.println("3. Update Year");
                        System.out.println("4. Update ISBN");
                        System.out.println("5. Update Genre");
                        System.out.println("6. Mark Unavailable");
                        System.out.println("7. Mark Available");
                        System.out.println("8. Print Book Info");
                        System.out.println("9. Exit");
                        System.out.println("+----------------------+");
                        System.out.println(">");
                        
                        input = scanner.nextLine().trim();
                        if(input.equalsIgnoreCase("9")) {
                            break;
                        }

                        // updates the book with the new info
                        switch (input.toLowerCase()) {
                            case "1": //    update title
                                System.out.println("Enter New Book Title:");
                                title = scanner.nextLine().trim();
                                book.updateBook(Optional.of(title), Optional.empty(),
                                        Optional.empty(),Optional.empty(),
                                        Optional.empty(),Optional.empty());
                                break;
                            case "2": //    update author
                                System.out.println("Enter New Book Author:");
                                bookAuthor = scanner.nextLine().trim();
                                book.updateBook(Optional.empty(), Optional.of(bookAuthor),
                                        Optional.empty(),Optional.empty(),
                                        Optional.empty(),Optional.empty());
                                break;
                            case "3": //    update year
                                System.out.println("Enter New Book Year:");
                                try {
                                    bookYear = scanner.nextInt();
                                } catch (Exception e) {
                                    System.out.println("Improper type:  " + e);
                                    continue;
                                }
                                book.updateBook(Optional.empty(), Optional.empty(),
                                        Optional.of(bookYear),Optional.empty(),
                                        Optional.empty(),Optional.empty());
                                break;
                            case "4": //    update ISBN
                                System.out.println("Enter New Book ISBN:");
                                bookISBN = scanner.nextLine().trim();
                                book.updateBook(Optional.empty(), Optional.empty(),
                                        Optional.empty(),Optional.of(bookISBN),
                                        Optional.empty(),Optional.empty());
                                break;
                            case "5": //   update genre
                                System.out.println("Enter New Book Genre:");
                                bookGenre = scanner.nextLine().trim();
                                book.updateBook(Optional.empty(), Optional.empty(),
                                        Optional.empty(),Optional.empty(),
                                        Optional.empty(),Optional.of(bookGenre));
                                break;
                            case "6": //    mark unavailable
                                System.out.println("Book marked unavailable");
                                book.updateBook(Optional.empty(), Optional.empty(),
                                        Optional.empty(),Optional.empty(),
                                        Optional.of(false),Optional.empty());
                                break;
                            case "7": //    mark available
                                System.out.println("Book marked available");
                                book.updateBook(Optional.empty(), Optional.empty(),
                                        Optional.empty(),Optional.empty(),
                                        Optional.of(true),Optional.empty());
                                break;
                            case "8": //   print book info
                                System.out.println("Book Info:");
                                book.getBookInfo();
                                break;
                            default: //    invalid option
                                System.out.println("Invalid option!");
                            }
                        }
                    }
                    printMenu();
                    break;
                case "4": //    add member
                    // asks for all necessary member info (name, email)
                    // constructor auto-generates memberID and empty borrowedBookList
                    System.out.println("Enter Member Name (Last, First)");
                    memberName = scanner.nextLine().trim();

                    System.out.println("Enter Member email");
                    memberEmail = scanner.nextLine().trim(); // we could maybe do a check for legit emails later?

                    member = library.addMember(memberName, memberEmail);
                    member.printMemberInfo();
                    printMenu();
                    break;
                case "5": //  remove member
                    // asks for a member's name and ID
                    // removes that member from the memberID list and allMembers list
                    System.out.println("Enter Member Name (Last, First)");
                    memberName = scanner.nextLine().trim();

                    System.out.println("Enter Member ID");
                    int memberID = Integer.parseInt(scanner.nextLine().trim());
                    member = library.getMember(memberName,memberID);
                    library.removeMember(member);
                    printMenu();
                    break;

                case "6": // checkout book
                    System.out.println("Enter Book Title:");
                    bookName = scanner.nextLine().trim().toLowerCase();
                    book = library.findBookIdByName(bookName);

                    System.out.println("Enter Member ID:");
                    int memId = Integer.parseInt(scanner.nextLine().trim());
                    member = library.getMember(null, memId);
                
                    if (book != null && member != null && book.checkAvailability()) {
                        library.checkoutBook(book, member);
                        book.updateBook(Optional.empty(), Optional.empty(), Optional.empty(), Optional.empty(), Optional.of(false), Optional.empty());
                        System.out.println("Book checked out successfully.");
                    } else {
                        System.out.println("Error: Book not found, unavailable, or member ID invalid.");
                    }
                    printMenu();
                    break;
                
                case "7": // return book
                    returnBook(library, scanner);
                    printMenu();
                    break;
                
                case "8": // print member info
                    System.out.println("Enter Member ID:");
                    int id = Integer.parseInt(scanner.nextLine().trim());
                    member = library.getMember(null, id);
                    if (member != null) {
                        member.printMemberInfo();
                    } else {
                        System.out.println("Member not found.");
                    }
                    printMenu();
                    break;
                case "9": // print all book names
                    System.out.println("Printing All Books List:");
                    List<Book> allBooks = library.getAllBooks();
                    for(Book thisBook : allBooks) {
                        thisBook.getBookInfo();
                    }
                    System.out.println();
                    break;
                default: // invalid command
                    System.out.println("Unknown command: " + input);
            }
        }


        scanner.close();
    }
    private void returnBook(Library library, Scanner scanner) {
        String bookName;
        Book book;
        System.out.println("Enter Book Title:");
        bookName = scanner.nextLine().trim().toLowerCase();
        book = library.findBookIdByName(bookName);
            
        if (book != null) {
            library.returnBook(book);
            book.updateBook(Optional.empty(), Optional.empty(), Optional.empty(), Optional.empty(), Optional.of(true), Optional.empty());
            System.out.println("Book returned successfully.");
        } else {
            System.out.println("Book not found.");
        }
    }
        public void printMenu(){
            System.out.println("choose number to select option");
            System.out.println("+-----------------------+");
            System.out.println("1. Add Book");
            System.out.println("2. Remove Book");
            System.out.println("3. Update Book");
            System.out.println("4. Add Member");
            System.out.println("5. Remove Member");
            System.out.println("6. Checkout Book");
            System.out.println("7. Return Book");
            System.out.println("8. Print Member Info");
            System.out.println("9. Print All Books List");
            System.out.println("10. Help");
            System.out.println("11. Exit");
            System.out.println("+-----------------------+");
        }
}

