package com.example;

import java.util.*;

class InterfaceRedone {
    public void doInterface(Library lib) {
        Scanner in = new Scanner(System.in);
        System.out.println("Input menu number to run command");
        printMenu();

        // switch case break statement for menu options
        while (true) {
            runSwitch(in, lib);
        }
    }

    public void printMenu() {
        System.out.println("+-----------------------+");
        System.out.println("1. Add Book");
        System.out.println("2. Remove Book");
        System.out.println("3. Update Book");
        System.out.println("4. Add Member");
        System.out.println("5. Remove Member");
        System.out.println("6. Checkout Book");
        System.out.println("7. Return Book");
        System.out.println("8. Print Member Info");
        System.out.println("9. Print All Books List");
        System.out.println("10. Help");
        System.out.println("11. Exit");
        System.out.println("+-----------------------+\n");
    }

    public void runSwitch(Scanner in, Library lib) {
        System.out.print("> ");
        String answer = in.nextLine();
        switch (answer) {
            case "1": // addBook
                addBook(in, lib);
                printMenu();
                break;
            case "2": // removeBook
            // removes a book with a given title from the library
                removeBook(in, lib);
                break;
            case "3": // updateBook

                break;
            case "4": // addMember

                break;
            case "5": // removeMember

                break;
            case "6": // checkoutBook

                break;
            case "7": // returnBook

                break;
            case "8": // printMemberInfo

                break;
            case "9": // printAllBookNames

                break;
            case "10": // printMemberInfo
                printMenu();
                break;
            default:
                System.out.println("IDK WHAT YOU'RE TYPING! " + in);
        }
    }

    private void removeBook(Scanner in, Library lib) {
        System.out.println("Enter Book Title");
        String input = in.nextLine().trim();
        String title = input.toLowerCase();
        Book book = lib.findBookIdByName(title);
        lib.removeBook(book);
        System.out.println("Book " + title + " has been removed\n\n");
    }

    private void addBook(Scanner scanner, Library lib) {
        // asks for all info about a book ands adds it to library book list
        // always sets new book to available and bookID is auto-generated by Book
        // constructor
        System.out.println("Enter Book Title");
        String input = scanner.nextLine().trim();
        String bookName = input.toLowerCase();

        System.out.println("Enter Book Author");
        input = scanner.nextLine().trim();
        String bookAuthor = input.toLowerCase();

        System.out.println("Enter Book Year");
        input = scanner.nextLine().trim();
        int bookYear = Integer.parseInt(input);

        System.out.println("Enter Book ISBN");
        String bookISBN = scanner.nextLine().trim();

        System.out.println("Enter Book Genre");
        input = scanner.nextLine().trim();
        String bookGenre = input.toLowerCase();

        Book book = new Book(bookName, bookAuthor, bookYear, bookISBN, bookGenre, lib);
        lib.addBook(book);
    }
}