package com.example;

public class LibraryAccounts {
    private double operatingCash = 39000.00;
    private Purchasing purchasing;
    private Librarians librarians;

    public LibraryAccounts(Purchasing purchasing, Librarians librarians) {
        this.operatingCash = 39000.0;
        this.purchasing = purchasing;
        this.librarians = librarians;
    }

    // returns the librarians class associated with this Library Accounts
    // useful for ensuring that correct instance of librarians is used when creating an interface instance
    public Librarians getLibrarians() {
        return librarians;
    }

    // donations of money can be added
    // returns a string describing the money added and the new balance
    // returns null if a negative amount of money tries to be donated
    public String addDonation(double amount){
        if (amount <= 0){
            System.out.println("Invalid donation amount.");
            return null;
        }
        operatingCash += amount;
        return String.format("Donation of $%.2f added. New balance: $%.2f", amount, operatingCash);
    }

    // Librarian can withdraw their salary
    // takes the name of the withdrawing librarian and a double amount that they are withdrawing
    // adds withdrawn salary to a librarians withdrawn salary
    // Returns a string describing the withdraw action outcome
    // returns null if withdraw amount is negative
    public String withdrawSalary(String librarianName, double amount) {
        if(amount <= 0 || amount > operatingCash){
            return null;
        }
        operatingCash -= amount;
        librarians.addWithdrawnSalary(librarianName, amount);
        return String.format("Salary withdrawn: $%.2f. New balance: $%.2f", amount, operatingCash);
    }

    // Librarian can order a book
    // takes the name of the purchasing librarian and the tile of the book they are withdrawing
    // returns a string describing this order
    // returns an error string if the cost of the book is negative or is more than operating cash
    // the cost of the book could is generated by purchasing
    public String orderBook(String librarianName, Book book){
        double cost = purchasing.generateRandomBookCost();
        if(cost <= 0){
            return null;
        }
        else if(cost > operatingCash){
            return String.format("Book cost: %.2f is higher than operating balance: %.2f", cost, operatingCash);
        }
        librarians.purchaseBook(librarianName, book, cost);
        return String.format("Book ordered: %s. Cost was: %.2f. New balance: $%.2f", book.getName(), cost, operatingCash);
    }

    // returns the current operating cash balance
    public double getOperatingCash(){
        return operatingCash;
    }
}
