package com.example;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

public class PurchasingTest {

    // tests that values generated by purchasing.generatedRandomBookCost()
    // are always inside the allowed range from 10.00 to 100.00
    @Test
    public void purchasingTest() {
        Purchasing testPurchasing = new Purchasing();

        int samples = 10000;
        double min = 10.0;
        double max = 100.0;

        for (int i = 0; i < samples; i++) {
            double value = testPurchasing.generateRandomBookCost();
            assertTrue(value >= min && value <= max, "Value out of range: " + value);
        }
    }
}
